tablist:
  header:
    - ""
    - "&a&l0b&c&l0t&9&l.org"
    - ""
    - "&6Is Currently Full"
    - "&6There are &l<>&r&6 in Queue "
    - ""
  footer:
    - ""
    - "&6You can donate to receive priority queue status, visit donate.0b0t.org"
    - ""