tablist:
  header:
    - ""
    - "&b&lCLOUDANARCHY.ORG"
    - ""
    - "&b&lIs Currently Full"
    - ""
    - "There are <> in Queue "
    - ""
  footer:
    - ""
    - "&7Contact: cloudanarchy@hackermail.com"
    - "&7Discussion: reddit.com/r/cloudanarchy/"
    - "&7Discord: http://discord.cloudanarchy.org"
    - "&7Donate: https://paypal.me/Krazzzzymonkey"
    - "&7Website: cloudanarchy.org (currently down)"
    - ""
    - "&7These are the only official cloud anarchy websites and contacts."