tablist:
  header:
    - ""
    - "&b&lCLOUDANARCHY.ORG"
    - ""
    - "&b&lHappy New Year"
    - ""
  footer:
    - ""
    - "&6Crafting Dupe Now Active!"
    - ""
    - "&a<players>&b players"
    - ""
    - "&7Donate: Type &f/donate &7for link"
    - "&7Discord: Type &f/discord &7for link"
    - "&7Contact: cloudanarchy@hackermail.com"
    - "&7Discussion: reddit.com/r/cloudanarchy/"
    - "&7Website: cloudanarchy.org (currently down)"
    -  ""
    - "&7These are the only official cloud anarchy websites and contacts."
#==========================================================================