name: '🚔'
on: [ push, pull_request ]
permissions:
  contents: write
jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: gradle/actions/wrapper-validation@v3

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          check-latest: true
          cache: 'gradle'

      - run: ./gradlew --console plain --no-daemon --full-stacktrace check build

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          body: 'automated release at commit ${{ github.sha }}'
          files: 'build/dist/*.jar'
